apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-2
  name: nginx-2
  namespace: s-madatov
spec:
  containers:
  - image: nginx
    name: nginx-2
    resources: {}
  dnsPolicy: ClusterFirst
